#!/usr/bin/env python
# import string
from random import choice
from wordlist import animal_list, adj_list

for index in range(0, 10):
    combo = "{} {} {}".format(choice(adj_list), choice(adj_list), choice(animal_list))
    combo = combo.replace("\n", "")
    combo = combo.replace("'", "")
    combo = combo.replace(",", "")
    combo = combo.title()
    combo = combo.replace(" ", "")
    print(combo + "\n")
